class_id(0..9).
:- class(X),  class(Y),  X < Y.
#modeh(class(const(class_id))).
#modeb(has_attr_0).
#modeb(has_attr_1).
#modeb(has_attr_2).
#modeb(has_attr_3).
#modeb(has_attr_4).
#modeb(has_attr_5).
#modeb(has_attr_6).
#modeb(has_attr_7).
#modeb(has_attr_8).
#modeb(has_attr_9).
#modeb(has_attr_10).
#modeb(has_attr_11).
#modeb(has_attr_12).
#modeb(has_attr_13).
#modeb(has_attr_14).
#modeb(has_attr_15).
#modeb(has_attr_16).
#modeb(has_attr_17).
#modeb(has_attr_18).
#modeb(has_attr_19).
#modeb(has_attr_20).
#modeb(has_attr_21).
#modeb(has_attr_22).
#modeb(has_attr_23).
#modeb(has_attr_24).
#modeb(has_attr_25).
#modeb(has_attr_26).
#modeb(has_attr_27).
#modeb(has_attr_28).
#modeb(has_attr_29).
#modeb(has_attr_30).
#modeb(has_attr_31).
#modeb(has_attr_32).
#modeb(has_attr_33).
#modeb(has_attr_34).
#modeb(has_attr_35).
#modeb(has_attr_36).
#modeb(has_attr_37).
#modeb(has_attr_38).
#modeb(has_attr_39).
#modeb(has_attr_40).
#bias("penalty(1, head).").
#bias("penalty(1, body(X)) :- in_body(X).").
