defaults:
  - _self_
  - environment: doc
  - model: config
  - training: base_parameter
  - webhook: webhook

hydra:
  run:
    dir: /vol/bitbucket/kg3217/cub_project/cub_3_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
