# Example config setup, create file of config.yaml with something like this
# defaults:
#   - _self_
#   - environment: ???
#   - model: config
#   - training: base_parameter
#   - webhook: webhook

# hydra:
#   job:
#      chdir: True # Hydra 1.2 onwards won't change dir so output will be dumped in work dir
#   run:
#     dir: ???
