defaults:
  - base_parameter

use_cuda: false
experiment_name: dnf_vanilla_ce_l1_mod
use_partial_cub: true
model_name: dnf_vanilla
partial_cub:
  partial_train_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/prepro/train.pkl
  partial_val_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/prepro/val.pkl
  partial_test_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/prepro/test.pkl

dnf_vanilla:
  optimiser: adam
  optimiser_lr: 0.001
  optimiser_weight_decay: 0.00004
  scheduler_step: 100
  loss_func: ce
  batch_size: 4
  epochs: 100
  initial_delta: 0.1
  delta_decay_delay: 10
  delta_decay_steps: 1
  delta_decay_rate: 1.1
  reg_fn: l1_mod
  reg_lambda: 0.3
