defaults:
  - base_parameter

experiment_name: dnf_eo
use_partial_cub: true
model_name: dnf_eo
partial_cub:
  partial_train_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/train_c3.pkl
  partial_val_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/val_c3.pkl
  partial_test_pkl: /vol/bitbucket/kg3217/cub_project/pkl_data/c3/test_c3.pkl

dnf_eo:
  optimiser: adam
  optimiser_lr: 0.001
  optimiser_weight_decay: 0.00004
  scheduler_step: 100
  loss_func: ce
  batch_size: 16
  epochs: 100
  initial_delta: 0.1
  delta_decay_delay: 5
  delta_decay_steps: 1
  delta_decay_rate: 1.1
  reg_lambda: 0.3
